#!/usr/bin/env python

# x2b - convert to binary

# Copyright (c) 2014 Jason Schulz <http://github.com/uxcn>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

'''x2b [-l | -u] [ 0b... | ... | 0... | 0x... ]'''

import sys

import os
import os.path

def usage():
    print(__doc__)
    sys.exit(1)

if len(sys.argv) != 2: 
    if len(sys.argv) != 3 or sys.argv[1] not in ['-l', '--lower', '-u', '--upper']:
        usage()

d = os.path.dirname(sys.argv[0])

x2x = os.path.join(d, 'x2x')

os.execv(x2x, [x2x, '-t', '2'] + sys.argv[1:])

# vim:ft=python:et:ts=4:sts=4:sw=4:tw=80
